### ISSUE TITLE
Project management to become more like Pyramid

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid_blogr#22]
In an effort to bring this project closer to the practices used in Pyramid, and help this project become an official Pyramid tutorial, I suggest the following:

- [x] Add a [contributing.md](https://help.github.com/articles/setting-guidelines-for-repository-contributors/). See [Pyramid's](https://github.com/Pylons/pyramid/blob/master/contributing.md)
- [x] Rename README.txt to README.rst
- [x] Automate building of docs (GitHub Services for ReadTheDocs)

**Comment by stevepiercy** [comment]
@blaflamme @pauleveritt @mcdonc @mmerickel @tseaver or any other Owner of the Pylons Project repos, neither I nor @ergo have permission to edit the settings for the repo Pylons/pyramid_blogr. Would one of you please:

* Visit https://github.com/Pylons/pyramid_blogr/settings/hooks
* Click Add service button
* Enter "ReadTheDocs" and submit the value

Other than #35, are there any other requirements that need to be fulfilled in order to bring this tutorial into the "official" Pyramid docs?

Thank you!

**Comment by mmerickel** [comment]
Please add me to the RTD project for these docs so I can mount it in the pylonsproject domain and update things in the future.

**Comment by stevepiercy** [comment]
@mmahesh Done!

**Comment by stevepiercy** [comment]
@mmerickel done!

**Comment by mmerickel** [comment]
http://docs.pylonsproject.org/projects/pyramid-blogr/en/latest/

**Comment by stevepiercy** [comment]
Thank you, @mmerickel. 

The docs don't autobuild on commit. It looks like the GitHub service has not yet been added.

**Comment by stevepiercy** [comment]
Looks like it's autobuilding now. Closing.
