### ISSUE TITLE
Suggestion: authentication form.

### ISSUE THREAD

**Issue by lemavri** [Pylons/pyramid_blogr#5]
The index.mako template in the [authentication topic](http://pyramid-blogr.readthedocs.org/en/latest/authentication.html) shows the following code:

```python
<%
from pyramid.security import authenticated_userid
user_id = authenticated_userid(request)
%>
```

I was wondering if it wouldn't be better to put that code in the views.py file instead, and send just the user_id variable to the template? I mean, to keep things in order.

PS: I'm loving your tutorial, I find it way better and clearer than the official one!

**Comment by ergo** [comment]
this is now obsolete, pyramid 1.5 version of tutorial does this differently :-)
