### ISSUE TITLE
forms.py not in views directory?

### ISSUE THREAD

**Issue by pauleveritt** [Pylons/pyramid_blogr#54]
Just a minor nit...curious why it is up there, instead of a helper in views? It is only consumed by code in views.

**Comment by ergo** [comment]
How would you suggest moving the code, I like to keep the forms code separate from views themselves - but I'm open for suggestions.

**Comment by pauleveritt** [comment]
Do you anticipate using the forms code from any consumer outside of the views directory? If so, leave it. If not, just as a suggestion, have views/form_helpers.py or just views/forms.py

**Comment by blaflamme** [comment]
I usually prefer a domain approach and also separate schemas and forms, but not in the case of wtforms. So I end up with something like:

- blog
- - __init__.py (having the includeme)
- - events.py
- - interfaces.py
- - models.py
- - schemas.py
- - services.py
- - subscribers.py
- - views.py

**Comment by ergo** [comment]
@pauleveritt I think i had some case of using form parsing outside of views - it was used in celery tasks to verify some data after parsing.

**Comment by pauleveritt** [comment]
Ok, let's close this then.
