### ISSUE TITLE
unable to host in production with Nginx

### ISSUE THREAD

**Issue by AlexanderMcNulty** [Pylons/pyramid_blogr#64]
In a shell:

```
$ git clone https://github.com/Pylons/pyramid_blogr.git
$ cd pyramid_blogr
$ python3.6 -m venv env
$ ./env/bin/pip3 install pyramid==1.7
$ ./env/bin/pip3 install -e .
$ initialize_pyramid_blogr_db development.ini
$ pserve development.ini
```

In another shell:

```
$ cat > nginx.conf <<EOF
events {
    worker_connections  1024;
}

http {
        server {
                listen 3456;
                location / {
                        proxy_pass http://127.0.0.1:6543;
                }
        }
}

daemon off;
EOF
$ nginx -c nginx.conf
```

Visit localhost:3456 in your web browser.

Notice the form on the page posts to 127.0.0.1:6543, a different host.

Expected the form to post to 127.0.0.1:3456.

--------

Hello,

Thank you very much for hosting this project. I have really enjoyed working with it thus far. 

In the past I have used Nginx to host my web applications in production. Unfortunately Nginx and Waitress don't seem to play nice. 

When hosting on 

> 'mytld.com' 

the "submit" button in register.jinja routes to 

> 127.0.0.1:6543

 as opposed to 

> 'mytld.com/'

this bug can be replicated using the https://github.com/Pylons/pyramid_blogr/ current commit (7abe5c1)

-------

P.S. I was able to evade this problem by using Caddy

**Comment by bertjwregeer** [comment]
You should be setting up the appropriate HTTP headers so that Waitress or whatever Python web-server you are using can set up the WSGI environment properly:

```
        proxy_set_header    Host $host;
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version  1.1;
        proxy_set_header    X-Forwarded-Proto $scheme;
```

For example will do the right thing. This is an NGINX configuration issue, not an issue with pyramid_blogr or with waitress, Caddy apparently forwards these headers already.
